apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"  # fixed typo: 'regrex' → 'regex'
spec:
  ingressClassName: nginx
  rules:
    - host: webapp.johnisah.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: phpapp-service
                port:
                  number: 80

    - host: phpmyadmin.johnisah.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: phpmyadmin-service
                port:
                  number: 80
